package org.oleg.ai.challenge.data.network.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * Represents a chat completion response from the OpenRouter API.
 *
 * @property id Unique identifier for this completion
 * @property provider The provider that handled the request
 * @property model The model that generated the completion
 * @property objectType The object type (typically "chat.completion")
 * @property created Unix timestamp of when the completion was created
 * @property choices List of completion choices
 * @property usage Token usage statistics
 */
@Serializable
data class ChatResponse(
    val id: String,
    val provider: String,
    val model: String,
    @SerialName("object")
    val objectType: String,
    val created: Long,
    val choices: List<ChatChoice>,
    val usage: Usage
)

/**
 * Represents a single completion choice in the response.
 *
 * @property logprobs Log probabilities (usually null)
 * @property finishReason The reason the completion finished
 * @property nativeFinishReason Provider-specific finish reason
 * @property index The index of this choice
 * @property message The message generated by the assistant
 */
@Serializable
data class ChatChoice(
    val logprobs: String? = null,
    @SerialName("finish_reason")
    val finishReason: String,
    @SerialName("native_finish_reason")
    val nativeFinishReason: String,
    val index: Int,
    val message: AssistantMessage
)

/**
 * Represents a message from the assistant in the response.
 *
 * @property role The role of the message (should be "assistant")
 * @property content The text content of the message
 */
@Serializable
data class AssistantMessage(
    val role: String,
    val content: ResponseContent
)

/**
 * Represents token usage statistics for a completion.
 *
 * @property promptTokens Number of tokens in the prompt
 * @property completionTokens Number of tokens in the completion
 * @property totalTokens Total number of tokens used
 */
@Serializable
data class Usage(
    @SerialName("prompt_tokens")
    val promptTokens: Int,
    @SerialName("completion_tokens")
    val completionTokens: Int,
    @SerialName("total_tokens")
    val totalTokens: Int
)

@Serializable
data class ResponseContent(
    val message: String,
    val instructions: List<Instructions>? = null,
)

@Serializable
sealed class Instructions {
    @Serializable
    data class CallTool(val name: String, val arguments: JsonObject, val isCompleted: Boolean) : Instructions()

    @Serializable
    data class CallAi(
        val expectedResultOfInstruction: String,
        val actualResultOfInstruction: String = "",
        val isCompleted: Boolean,
    ) : Instructions()
}
