package org.oleg.ai.challenge.data.network.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a chat completion response from the OpenRouter API.
 *
 * @property id Unique identifier for this completion
 * @property provider The provider that handled the request
 * @property model The model that generated the completion
 * @property objectType The object type (typically "chat.completion")
 * @property created Unix timestamp of when the completion was created
 * @property choices List of completion choices
 * @property usage Token usage statistics
 */
//@Serializable
//data class ChatResponse(
//    val id: String,
//    val provider: String? = null,
//    val model: String,
//    @SerialName("object")
//    val objectType: String,
//    val created: Long,
//    val choices: List<ChatChoice>,
//    val usage: Usage
//)

@Serializable
data class ChatResponse(
    val model: String,
    @SerialName("created_at")
    val createdAt: String,
    val message: OllamaMessage,
    val done: Boolean,
    @SerialName("done_reason")
    val doneReason: String? = null,
    @SerialName("total_duration")
    val totalDuration: Long? = null,
    @SerialName("load_duration")
    val loadDuration: Long? = null,
    @SerialName("prompt_eval_count")
    val promptEvalCount: Int? = null,
    @SerialName("prompt_eval_duration")
    val promptEvalDuration: Long? = null,
    @SerialName("eval_count")
    val evalCount: Int? = null,
    @SerialName("eval_duration")
    val evalDuration: Long? = null
)

@Serializable
data class OllamaMessage(
    val role: String,
    val content: String,
    @SerialName("tool_calls")
    val toolCalls: List<ToolCall>? = null
)

/**
 * Represents a tool call requested by the AI model.
 *
 * @property id Unique identifier for this tool call
 * @property type The type of tool call (always "function")
 * @property function The function call details
 */
@Serializable
data class ToolCall(
    val id: String,
    val type: String = "function",
    val function: FunctionCall
)

/**
 * Represents a function call from the AI model.
 *
 * @property name The name of the function to call
 * @property arguments JSON string containing the function arguments
 */
@Serializable
data class FunctionCall(
    val name: String,
    val arguments: String
)

/**
 * Represents a single completion choice in the response.
 *
 * @property logprobs Log probabilities (usually null)
 * @property finishReason The reason the completion finished
 * @property nativeFinishReason Provider-specific finish reason
 * @property index The index of this choice
 * @property message The message generated by the assistant
 */
@Serializable
data class ChatChoice(
    val logprobs: String? = null,
    @SerialName("finish_reason")
    val finishReason: String,
    @SerialName("native_finish_reason")
    val nativeFinishReason: String? = null,
    val index: Int,
    val message: AssistantMessage
)

/**
 * Represents a message from the assistant in the response.
 *
 * @property role The role of the message (should be "assistant")
 * @property content The text content of the message
 */
@Serializable
data class AssistantMessage(
    val role: String,
    val content: String
)

/**
 * Represents token usage statistics for a completion.
 *
 * @property promptTokens Number of tokens in the prompt
 * @property completionTokens Number of tokens in the completion
 * @property totalTokens Total number of tokens used
 */
@Serializable
data class Usage(
    @SerialName("prompt_tokens")
    val promptTokens: Int,
    @SerialName("completion_tokens")
    val completionTokens: Int,
    @SerialName("total_tokens")
    val totalTokens: Int
)
